-- ═══════════════════════════════════════════════════════════════════════
-- EcoQuiz — Inserción de 30 preguntas educativas
-- Ejecutar en: Dashboard → SQL Editor → New query → Pegar → Run
-- ═══════════════════════════════════════════════════════════════════════

-- ── Bioma 0: Ciudad y Medio Ambiente ────────────────────────────────
INSERT INTO questions (level_id, question_text, image_url, options, correct_index, hint, fun_fact) VALUES
(0, '¿Cuál es la regla de las 3 R para cuidar el medio ambiente?', 'assets/images/eco_ajolote_mascot.png', '["Robar, Romper, Reír", "Reducir, Reutilizar, Reciclar", "Rápido, Ruidoso, Raro"]', 1, 'Son acciones para generar menos basura.', 'Reciclar una lata de aluminio ahorra suficiente energía para encender una TV por 3 horas.'),
(0, '¿Cuánto tarda en degradarse una botella de plástico en la naturaleza?', 'assets/images/eco_ajolote_mascot.png', '["1 mes", "10 años", "Hasta 500 años"]', 2, 'Es muchísimo tiempo... más que la vida de tus abuelos.', 'Cada año se producen 500 mil millones de botellas de plástico en el mundo. ¡Usa tu botella reutilizable!'),
(0, '¿Qué tipo de energía producen los paneles solares?', 'assets/images/eco_ajolote_mascot.png', '["Energía del viento", "Energía limpia del Sol", "Energía de la basura"]', 1, 'Tienen que ver con la estrella más brillante del cielo.', 'México es uno de los países con más radiación solar del mundo. ¡En el desierto de Sonora hay enormes parques solares!'),
(0, '¿Qué es la contaminación del aire que se ve como una nube gris sobre la ciudad?', 'assets/images/eco_ajolote_mascot.png', '["Niebla marina", "Smog", "Vapor de agua"]', 1, 'Su nombre combina las palabras "smoke" (humo) y "fog" (niebla) en inglés.', 'La Ciudad de México fue una de las ciudades más contaminadas del mundo, pero gracias a programas como "Hoy No Circula" ha mejorado mucho.'),
(0, '¿Cuál es la mejor manera de ahorrar agua en casa?', 'assets/images/eco_ajolote_mascot.png', '["Dejar la llave abierta", "Cerrar la llave mientras te lavas los dientes", "Usar más agua caliente"]', 1, 'Piensa en lo que haces cuando te cepillas los dientes por la mañana.', 'Si cierras la llave mientras te lavas los dientes, ahorras hasta 12 litros de agua cada vez. ¡Eso llena 24 botellas!'),

-- ── Bioma 1: Manglar ────────────────────────────────────────────────
(1, '¿Qué característica especial tienen los árboles del manglar?', 'assets/images/eco_ajolote_mascot.png', '["Crecen en la nieve", "Sus raíces crecen en agua salada", "No necesitan agua"]', 1, 'Viven donde se junta el río con el mar.', 'Los manglares protegen las costas de los huracanes como si fueran escudos naturales.'),
(1, '¿Qué ave de color rosa vive en los manglares de Yucatán?', 'assets/images/eco_ajolote_mascot.png', '["Colibrí", "Flamenco", "Loro"]', 1, 'Su color se debe a los camarones que come.', 'Los flamencos del Caribe obtienen su color rosa de los pigmentos de los pequeños camarones que comen. ¡Si dejaran de comerlos se volverían blancos!'),
(1, '¿Por qué los manglares son tan importantes para los peces?', 'assets/images/eco_ajolote_mascot.png', '["Les dan sombra del sol", "Son la guardería donde nacen y crecen", "Los pintan de colores"]', 1, 'Muchos peces bebés crecen protegidos entre las raíces.', 'El 75% de los peces que se pescan en México pasaron su infancia en un manglar. ¡Sin manglares no habría pesca!'),
(1, '¿Qué reptil grande vive en los manglares de Veracruz y Tabasco?', 'assets/images/eco_ajolote_mascot.png', '["Iguana marina", "Cocodrilo", "Tortuga gigante"]', 1, 'Es un reptil con una mordida muy poderosa y muchos dientes.', 'El cocodrilo de pantano mexicano puede medir hasta 3.5 metros. A pesar de su tamaño, es muy importante para mantener sanos los manglares.'),
(1, '¿Qué pasa cuando se destruye un manglar?', 'assets/images/eco_ajolote_mascot.png', '["No pasa nada", "Las costas quedan desprotegidas de tormentas", "Llueve más"]', 1, 'Los manglares funcionan como un muro natural contra el mar.', 'México ha perdido más del 10% de sus manglares. Por eso existen leyes que los protegen como ecosistemas prioritarios.'),

-- ── Bioma 2: Arrecife de Coral ──────────────────────────────────────
(2, '¿Los corales del arrecife son plantas o animales?', 'assets/images/quiz_turtle_1778463514370.png', '["Plantas", "Animales", "Piedras de colores"]', 1, 'Aunque no se mueven de lugar, están vivos y comen plancton.', 'Los corales son en realidad animales diminutos llamados pólipos que construyen grandes esqueletos de calcio.'),
(2, '¿Cuál es el arrecife de coral más grande de México?', 'assets/images/quiz_turtle_1778463514370.png', '["Arrecife de Cozumel", "Arrecife Mesoamericano", "Arrecife del Pacífico"]', 1, 'Se extiende desde Quintana Roo hasta Honduras.', 'El Arrecife Mesoamericano es el segundo más grande del mundo, después de la Gran Barrera de Coral de Australia. ¡Mide más de 1,000 km!'),
(2, '¿Cuál es el pez más grande del mundo que visita los arrecifes de México?', 'assets/images/quiz_turtle_1778463514370.png', '["Delfín", "Tiburón ballena", "Pez payaso"]', 1, 'Tiene el nombre de dos animales juntos y es enorme pero inofensivo.', 'El tiburón ballena puede medir hasta 12 metros, ¡como un camión! A pesar de su tamaño, solo come plancton y es totalmente inofensivo.'),
(2, '¿Qué le pasa a los corales cuando el agua del mar se calienta demasiado?', 'assets/images/quiz_turtle_1778463514370.png', '["Crecen más rápido", "Se ponen blancos y pueden morir", "Se vuelven más fuertes"]', 1, 'El calentamiento global es un problema para ellos.', 'Cuando los corales se estresan por el calor, expulsan las algas que les dan color y se ponen blancos. Esto se llama "blanqueamiento" y puede matarlos.'),
(2, '¿Qué tortuga marina pone sus huevos en las playas de Quintana Roo?', 'assets/images/quiz_turtle_1778463514370.png', '["Tortuga caguama", "Tortuga mordedora", "Tortuga de orejas rojas"]', 0, 'Es una tortuga marina que viaja miles de kilómetros para volver a la playa donde nació.', 'Las tortugas caguama pueden viajar más de 12,000 km para volver a la misma playa donde nacieron. ¡Tienen un GPS natural en su cerebro!'),

-- ── Bioma 3: Bosque de Pinos ────────────────────────────────────────
(3, '¿Qué asombroso animal migra miles de kilómetros hacia los bosques de México?', 'assets/images/quiz_butterfly_1778463527262.png', '["Oso pardo", "Mariposa Monarca", "Pingüino Emperador"]', 1, 'Es un insecto volador de color naranja y negro.', 'La mariposa monarca viaja desde Canadá hasta los bosques de Michoacán cada invierno. ¡Recorre más de 4,000 km!'),
(3, '¿En qué estado de México llegan las mariposas monarca cada invierno?', 'assets/images/quiz_butterfly_1778463527262.png', '["Sonora", "Michoacán", "Quintana Roo"]', 1, 'Es famoso por sus bosques de oyamel y su deliciosa gastronomía.', 'Los bosques de oyamel en Michoacán se llenan de millones de mariposas monarca entre noviembre y marzo. ¡Los árboles se ven completamente anaranjados!'),
(3, '¿Qué producen los bosques que nosotros necesitamos para respirar?', 'assets/images/quiz_butterfly_1778463527262.png', '["Dióxido de carbono", "Oxígeno", "Humo"]', 1, 'Los árboles absorben CO₂ y liberan algo que respiramos.', 'Un solo árbol grande produce suficiente oxígeno para que respiren 4 personas durante un año entero.'),
(3, '¿Qué animal único en el mundo vive en los lagos de Xochimilco, México?', 'assets/images/eco_ajolote_mascot.png', '["Ajolote", "Delfín rosa", "Pez globo"]', 0, '¡Es la mascota de EcoQuiz! Tiene branquias externas como plumas en su cabeza.', 'El ajolote puede regenerar sus patas, cola, corazón e incluso partes de su cerebro. ¡Los científicos lo estudian para aprender sobre la regeneración!'),
(3, '¿Qué tipo de árboles predominan en los bosques templados de México?', 'assets/images/quiz_butterfly_1778463527262.png', '["Palmeras", "Pinos y encinos", "Cactus gigantes"]', 1, 'Son árboles que no pierden sus hojas en invierno y huelen muy bien.', 'México tiene más de 50 especies de pinos, más que cualquier otro país del mundo. ¡Somos la capital mundial de los pinos!'),

-- ── Bioma 4: Selva Tropical ─────────────────────────────────────────
(4, '¿Cuál de estos felinos vive en la selva mexicana y sabe nadar muy bien?', 'assets/images/quiz_jaguar_1778457575331.png', '["Jaguar", "León africano", "Gato doméstico"]', 0, 'Tiene hermosas manchas llamadas rosetas en su piel.', 'El jaguar es el felino más grande de toda América y el tercero más grande del mundo, después del tigre y el león.'),
(4, '¿Qué ave de la selva tiene un pico enorme y muy colorido?', 'assets/images/quiz_toucan_1778462119800.png', '["Águila real", "Tucán", "Golondrina"]', 1, 'Su pico puede ser tan largo como su cuerpo y tiene colores brillantes.', 'El pico del tucán es hueco por dentro y le sirve para regular su temperatura corporal. ¡Es como un radiador natural!'),
(4, '¿Qué ave sagrada de los mayas tiene plumas verdes brillantes?', 'assets/images/eco_ajolote_mascot.png', '["Colibrí", "Quetzal", "Guacamaya"]', 1, 'Los mayas la consideraban el ave más hermosa y sagrada de todas.', 'El quetzal era tan importante para los mayas que usaban sus plumas como moneda. Arrancárselas era un crimen castigado con la muerte.'),
(4, '¿Por qué llueve tanto en la selva tropical?', 'assets/images/quiz_jaguar_1778457575331.png', '["Porque tiene muchos ríos", "Por el calor y la humedad que forman nubes", "Porque está cerca del polo norte"]', 1, 'El aire caliente sube y forma muchas nubes de lluvia.', 'La Selva Lacandona de Chiapas recibe hasta 3,000 mm de lluvia al año. ¡Eso es como llenar una alberca de 3 metros de profundidad!'),
(4, '¿Qué árbol gigante es conocido como el "árbol de la vida" en la selva maya?', 'assets/images/eco_ajolote_mascot.png', '["Manzano", "Ceiba", "Sauce llorón"]', 1, 'Los mayas creían que conectaba el cielo con el inframundo.', 'La ceiba puede crecer hasta 70 metros de alto. Los mayas la consideraban sagrada y jamás la cortaban. ¡Es el árbol nacional de Guatemala!'),

-- ── Bioma 5: Desierto ───────────────────────────────────────────────
(5, '¿Dónde almacenan el agua los cactus para sobrevivir en el desierto?', 'assets/images/quiz_fox_1778463541718.png', '["En sus flores", "En sus raíces", "En sus gruesos tallos verdes"]', 2, 'Es la parte grande, verde y carnosa de la planta.', '¡Un cactus gigante llamado Saguaro puede almacenar hasta 5,000 litros de agua en su interior!'),
(5, '¿Por qué muchos animales del desierto salen de noche y duermen de día?', 'assets/images/quiz_fox_1778463541718.png', '["Porque les gusta la luna", "Para evitar el calor extremo del día", "Porque son tímidos"]', 1, 'Durante el día la temperatura puede llegar a más de 50°C.', 'En el desierto de Sonora, la temperatura puede llegar a 50°C de día y bajar hasta 0°C en la noche. ¡Una diferencia de 50 grados!'),
(5, '¿Qué ave aparece en el escudo de la bandera de México?', 'assets/images/eco_ajolote_mascot.png', '["Colibrí", "Águila real", "Halcón peregrino"]', 1, 'Está parada sobre un nopal devorando una serpiente.', 'El águila real puede volar a velocidades de hasta 300 km/h cuando se lanza en picada. ¡Es una de las aves más rápidas del mundo!'),
(5, '¿Cómo se protege el armadillo cuando se siente en peligro?', 'assets/images/eco_ajolote_mascot.png', '["Corre muy rápido", "Se enrolla en una bola con su caparazón", "Escupe veneno"]', 1, 'Tiene una armadura natural hecha de placas duras.', 'El armadillo de nueve bandas es el único animal además del humano que puede contraer lepra. ¡Por eso los científicos los estudian para encontrar curas!'),
(5, '¿Qué es un oasis en el desierto?', 'assets/images/quiz_fox_1778463541718.png', '["Una tormenta de arena", "Un lugar con agua y vegetación en medio del desierto", "Un tipo de cactus"]', 1, 'Es como un pequeño paraíso verde donde los viajeros pueden beber agua.', 'En Baja California Sur existe un oasis real llamado San Ignacio con más de 80,000 palmeras. ¡Los misioneros lo descubrieron hace 300 años!');
