-- ═══════════════════════════════════════════════════════════════════════
-- EcoQuiz — Inserción de 150 preguntas educativas (5 por nodo)
-- Ejecutar en: Supabase Dashboard → SQL Editor → New query → Pegar → Run
-- ═══════════════════════════════════════════════════════════════════════

-- Limpiar preguntas anteriores para evitar duplicados
DELETE FROM questions;

-- ── GENERAR LOS 30 NIVELES (NODOS) ────────────────────────────────────
-- Esto asegura que los niveles del 0 al 29 existan en la tabla levels 
-- para no romper la llave foránea al insertar las preguntas.
INSERT INTO levels (id, title, biome, order_index, is_active) VALUES
(0, 'Nodo 1', 'Ciudad', 0, true), (1, 'Nodo 2', 'Ciudad', 1, true), (2, 'Nodo 3', 'Ciudad', 2, true), (3, 'Nodo 4', 'Ciudad', 3, true), (4, 'Nodo 5', 'Ciudad', 4, true),
(5, 'Nodo 1', 'Manglar', 5, true), (6, 'Nodo 2', 'Manglar', 6, true), (7, 'Nodo 3', 'Manglar', 7, true), (8, 'Nodo 4', 'Manglar', 8, true), (9, 'Nodo 5', 'Manglar', 9, true),
(10, 'Nodo 1', 'Arrecife', 10, true), (11, 'Nodo 2', 'Arrecife', 11, true), (12, 'Nodo 3', 'Arrecife', 12, true), (13, 'Nodo 4', 'Arrecife', 13, true), (14, 'Nodo 5', 'Arrecife', 14, true),
(15, 'Nodo 1', 'Bosque', 15, true), (16, 'Nodo 2', 'Bosque', 16, true), (17, 'Nodo 3', 'Bosque', 17, true), (18, 'Nodo 4', 'Bosque', 18, true), (19, 'Nodo 5', 'Bosque', 19, true),
(20, 'Nodo 1', 'Selva', 20, true), (21, 'Nodo 2', 'Selva', 21, true), (22, 'Nodo 3', 'Selva', 22, true), (23, 'Nodo 4', 'Selva', 23, true), (24, 'Nodo 5', 'Selva', 24, true),
(25, 'Nodo 1', 'Desierto', 25, true), (26, 'Nodo 2', 'Desierto', 26, true), (27, 'Nodo 3', 'Desierto', 27, true), (28, 'Nodo 4', 'Desierto', 28, true), (29, 'Nodo 5', 'Desierto', 29, true)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title, biome = EXCLUDED.biome, is_active = EXCLUDED.is_active;

-- ── BIOMA 1: CIUDAD (Niveles 0 al 4) ──────────────────────────────────
INSERT INTO questions (level_id, question_text, options, correct_index, hint, fun_fact) VALUES
-- Nivel 0
(0, '¿Qué significa la regla de las 3 R?', '["Reír, Relajar, Respirar", "Reducir, Reutilizar, Reciclar", "Rápido, Ruidoso, Riesgoso"]', 1, 'Son acciones para cuidar el planeta.', 'Reciclar una lata de aluminio ahorra suficiente energía para encender una TV por 3 horas.'),
(0, '¿Cuál de estos materiales es reciclable?', '["Cáscara de plátano", "Papel higiénico usado", "Botella de plástico limpio"]', 2, 'Piensa en qué cosas pueden volver a fundirse.', 'El plástico tarda hasta 500 años en degradarse en la naturaleza.'),
(0, '¿Qué tipo de contaminación producen los coches?', '["Contaminación acústica y del aire", "Contaminación visual", "Contaminación del suelo"]', 0, 'Involucra el humo y el ruido del motor.', 'Un auto emite en promedio 4.6 toneladas métricas de dióxido de carbono al año.'),
(0, '¿Qué contenedor se usa para el vidrio?', '["Contenedor verde", "Contenedor amarillo", "Contenedor azul"]', 0, 'Es del color de los árboles.', 'El vidrio es 100% reciclable y puede reciclarse infinitamente.'),
(0, '¿Cuál es una forma de ahorrar agua en casa?', '["Dejar la llave abierta al lavarse los dientes", "Bañarse en 5 minutos", "Lavar el coche con manguera"]', 1, 'Mientras menos tiempo esté el agua corriendo, mejor.', 'Bañarse en 5 minutos puede ahorrar hasta 3,500 litros de agua al mes.'),
-- Nivel 1
(1, '¿Qué es el compostaje?', '["Plantar árboles nuevos", "Crear abono con restos de comida", "Limpiar la calle"]', 1, 'Involucra los residuos orgánicos.', 'El compostaje reduce la basura de los vertederos en un 30%.'),
(1, '¿Por qué es bueno usar bicicleta en la ciudad?', '["Porque contamina menos que un auto", "Porque es más ruidosa", "Porque usa gasolina especial"]', 0, 'No usa combustibles fósiles.', 'Usar bicicleta también mejora tu salud cardiovascular.'),
(1, '¿Qué puedes hacer con la ropa que ya no usas?', '["Tirarla a la basura", "Quemar la ropa", "Donarla o reciclarla"]', 2, 'Alguien más puede darle un segundo uso.', 'La industria textil es la segunda más contaminante del mundo.'),
(1, '¿Qué son los residuos orgánicos?', '["Pilas y baterías", "Restos de frutas y verduras", "Bolsas de plástico"]', 1, 'Son cosas que provienen de la naturaleza y se pudren.', 'Los residuos orgánicos pueden usarse para fertilizar plantas.'),
(1, '¿Cuál de estos consume electricidad incluso apagado?', '["Un libro", "Una vela", "Un televisor conectado"]', 2, 'Se le llama consumo "vampiro".', 'Los aparatos conectados sin uso pueden representar el 10% de tu recibo de luz.'),
-- Nivel 2
(2, '¿Qué son los gases de efecto invernadero?', '["Gases que atrapan el calor en la atmósfera", "Gases que huelen a flores", "Gases que enfrían la Tierra"]', 0, 'Funcionan como los cristales de un invernadero real.', 'El dióxido de carbono es el gas de efecto invernadero más abundante.'),
(2, '¿Qué energía es más amigable en la ciudad?', '["Energía de carbón", "Energía solar", "Energía nuclear"]', 1, 'Proviene de una estrella brillante.', 'La energía solar no produce emisiones tóxicas durante su uso.'),
(2, '¿Por qué debemos plantar árboles urbanos?', '["Para que ensucien las calles", "Para dar sombra y limpiar el aire", "Para tener donde chocar"]', 1, 'Ayudan a respirar mejor y refrescan la ciudad.', 'Un árbol grande puede absorber hasta 150 kg de CO2 al año.'),
(2, '¿Qué pasa si tiramos aceite por el fregadero?', '["Contamina miles de litros de agua", "Hace que las tuberías huelan bien", "No pasa nada"]', 0, 'El agua y el aceite no se mezclan, y afecta a los ríos.', 'Un solo litro de aceite usado puede contaminar mil litros de agua.'),
(2, '¿Cuál bolsa es mejor usar en el supermercado?', '["Bolsa de plástico", "Bolsa de tela reutilizable", "Bolsa de papel nueva cada vez"]', 1, 'La que puedes usar muchas veces.', 'Una bolsa de tela puede reemplazar cientos de bolsas plásticas.'),
-- Nivel 3
(3, '¿Qué transporte público es más ecológico?', '["Autobús de diésel antiguo", "Metro o tranvía eléctrico", "Taxis privados a gasolina"]', 1, 'El que no quema combustible en las calles.', 'Los trenes eléctricos son de los transportes masivos más limpios.'),
(3, '¿Qué significa "huella de carbono"?', '["La marca que dejamos al caminar en lodo", "El impacto ambiental de nuestras acciones", "Un tipo de zapato"]', 1, 'Es la cantidad de emisiones que generamos.', 'Reducir el consumo de carne disminuye tu huella de carbono.'),
(3, '¿Dónde debes tirar las pilas gastadas?', '["En el jardín", "En la basura normal", "En contenedores especiales"]', 2, 'Las pilas tienen químicos peligrosos que requieren tratamiento.', 'Una sola pila de botón puede contaminar 600 mil litros de agua.'),
(3, '¿Qué es el "smog"?', '["Una nube blanca y limpia", "Nube de contaminación sobre la ciudad", "Un tipo de lluvia"]', 1, 'Es la mezcla de niebla y humo contaminante.', 'El smog puede causar enfermedades respiratorias graves.'),
(3, '¿Qué ayuda a reducir la basura electrónica?', '["Reparar aparatos en lugar de tirarlos", "Comprar un celular nuevo cada mes", "Quemar los cables"]', 0, 'Dale más vida útil a tus dispositivos.', 'La basura electrónica es la que más rápido crece en el mundo.'),
-- Nivel 4
(4, '¿Qué beneficio tiene comprar comida local?', '["Contamina menos por transporte", "Es de plástico", "No tiene beneficio"]', 0, 'Los alimentos viajan menos distancia.', 'Comprar local también apoya la economía de tu comunidad.'),
(4, '¿Por qué son importantes los parques en la ciudad?', '["Son pulmones verdes que dan oxígeno", "Solo sirven para hacer ruido", "Son lugares para tirar basura"]', 0, 'Actúan como filtros gigantes de aire.', 'Vivir cerca de un parque mejora la salud mental.'),
(4, '¿Cómo puedes reducir el uso de plástico?', '["Usando botella de agua reutilizable", "Comprando agua embotellada diario", "Pidiendo muchos popotes"]', 0, 'Usa un recipiente que puedas lavar.', 'Se venden un millón de botellas de plástico cada minuto en el mundo.'),
(4, '¿Qué es la "contaminación lumínica"?', '["Exceso de luz artificial que afecta a animales", "Luces de Navidad bonitas", "Falta de luz en la calle"]', 0, 'Es cuando no se pueden ver las estrellas por tanta luz.', 'Afecta la migración de aves y la vida de los insectos.'),
(4, '¿Por qué apagar la luz al salir del cuarto?', '["Para asustar a alguien", "Para ahorrar energía", "Porque la bombilla se cansa"]', 1, 'Ayuda a consumir menos recursos del planeta.', 'Apagar luces innecesarias es el paso más fácil para ser ecológico.');

-- ── BIOMA 2: MANGLAR (Niveles 5 al 9) ──────────────────────────────────
INSERT INTO questions (level_id, question_text, options, correct_index, hint, fun_fact) VALUES
-- Nivel 5
(5, '¿Qué es un manglar?', '["Un bosque en el desierto", "Un ecosistema costero de árboles tolerantes a la sal", "Una montaña nevada"]', 1, 'Crecen donde el río se encuentra con el mar.', 'Los manglares protegen las costas de los huracanes.'),
(5, '¿Cómo respiran las raíces de los mangles?', '["A través de tubos de oxígeno artificial", "No respiran", "Con raíces aéreas llamadas neumatóforos"]', 2, 'Son raíces que salen del lodo hacia arriba.', 'Los neumatóforos actúan como tubos de snorkel.'),
(5, '¿Por qué los manglares son importantes para los peces?', '["Son guarderías seguras para crías", "Son lugares calientes para nadar", "No hay peces ahí"]', 0, 'Las raíces enredadas ofrecen escondites.', 'El 75% de los peces comerciales pasan parte de su vida en manglares.'),
(5, '¿A qué animal le encanta vivir en los manglares mexicanos?', '["Al pingüino", "Al cocodrilo", "Al oso polar"]', 1, 'Es un gran reptil de dientes afilados.', 'Los cocodrilos ayudan a mantener el equilibrio en este ecosistema.'),
(5, '¿Qué tipo de agua hay en el manglar?', '["Dulce", "Salada", "Salobre (mezcla de dulce y salada)"]', 2, 'Es el punto de encuentro entre el río y el océano.', 'Los mangles pueden filtrar la sal a través de sus hojas.'),
-- Nivel 6
(6, '¿Cómo ayudan los manglares frente a tsunamis?', '["Frenan la fuerza de las olas", "Hacen que la ola sea más grande", "No hacen nada"]', 0, 'Actúan como una barrera o escudo natural.', 'Los manglares reducen la fuerza de las olas en un 66%.'),
(6, '¿Qué es el "carbono azul"?', '["Carbono pintado de azul", "El carbono almacenado en ecosistemas costeros", "Un tipo de gema"]', 1, 'Es el que guardan los manglares y pastos marinos.', 'Los manglares almacenan hasta 4 veces más carbono que un bosque normal.'),
(6, '¿Cuál es la principal amenaza humana para el manglar?', '["Plantar muchos árboles", "La deforestación para granjas camaroneras", "Los cocodrilos"]', 1, 'Se cortan para criar crustáceos comerciales.', 'Casi el 35% de los manglares del mundo han desaparecido en 20 años.'),
(6, '¿De qué color suele ser el mangle rojo?', '["Verde fosforescente", "Grisáceo", "Sus raíces tienen un tono rojizo"]', 2, 'Su nombre te da la pista del color de su corteza/raíz.', 'El mangle rojo es el que está más cerca del agua profunda.'),
(6, '¿Qué ave de patas largas habita los manglares?', '["La garza", "El águila calva", "El avestruz"]', 0, 'Pesca de pie en aguas poco profundas.', 'Las garzas construyen sus nidos en lo alto de los árboles del manglar.'),
-- Nivel 7
(7, '¿Qué función cumple el fango del manglar?', '["Almacenar carbono y filtrar agua", "Ensuciar a los animales", "Ser material de construcción humano"]', 0, 'Es un filtro natural gigante.', 'El lodo del manglar es negro porque casi no tiene oxígeno.'),
(7, '¿Por qué los cangrejos son vitales en el manglar?', '["Para comerse a los mangles", "Reciclan nutrientes excavando y comiendo hojas", "No son vitales"]', 1, 'Son los jardineros del lodo.', 'Existen cangrejos trepadores que viven en las ramas del mangle.'),
(7, '¿Qué sucede si se destruye un manglar?', '["La costa se erosiona más rápido", "Habrá más peces", "El agua se vuelve más limpia"]', 0, 'La tierra se desmorona hacia el mar.', 'Sin manglares, muchas comunidades costeras se inundarían fácilmente.'),
(7, '¿Qué tipo de adaptación tienen las semillas del mangle rojo?', '["Germinan cuando están secas", "Germinan mientras siguen en el árbol materno", "Tienen alas de murciélago"]', 1, 'Se llama "viviparidad", como en los mamíferos.', 'Estas semillas flotan hasta encontrar lodo donde clavar su raíz.'),
(7, '¿Dónde se encuentran los manglares en el mundo?', '["Zonas tropicales y subtropicales", "Zonas polares", "En desiertos secos"]', 0, 'Les gusta el calor y el agua.', 'Indonesia tiene la mayor extensión de manglares del mundo.'),
-- Nivel 8
(8, '¿Qué contaminante daña mucho a los manglares?', '["El oxígeno", "El derrame de petróleo", "La luz solar"]', 1, 'Es una sustancia negra y espesa usada como combustible.', 'El petróleo asfixia las raíces de los manglares bloqueando sus poros.'),
(8, '¿Cómo filtran la sal los manglares?', '["La excretan por las hojas", "No la filtran", "Usan filtros de café"]', 0, 'Si miras una hoja de mangle de cerca, verás cristales blancos.', 'Puedes saborear la sal si lames la hoja de algunas especies de mangle.'),
(8, '¿Qué ave famosa por su color rosado vive cerca de manglares?', '["El pelícano", "El flamenco", "El pingüino"]', 1, 'Comen pequeños crustáceos que les dan su color.', 'Su pico está diseñado para filtrar el barro y atrapar comida.'),
(8, '¿Qué es un estero?', '["Una estrella fugaz", "Un cuerpo de agua donde el río desemboca en el mar", "Un bosque de pinos"]', 1, 'Es el hogar principal de los manglares.', 'Los esteros son zonas de alta productividad biológica.'),
(8, '¿Cómo ayuda el manglar a los arrecifes de coral?', '["Atrapan sedimentos para que no asfixien al coral", "Le dan sombra al coral", "Se comen al coral"]', 0, 'Actúan como un colador para la tierra que baja de los ríos.', 'Los manglares y corales son ecosistemas hermanos que se protegen mutuamente.'),
-- Nivel 9
(9, '¿Se puede restaurar un manglar destruido?', '["No, jamás", "Sí, replantando y restaurando el flujo de agua", "Sí, pero tarda un millón de años"]', 1, 'Con esfuerzo humano, pueden volver a crecer.', 'La restauración de manglares es clave para combatir el cambio climático.'),
(9, '¿Qué mamífero acuático pacífico suele visitar los manglares?', '["El tiburón blanco", "El manatí", "La ballena azul"]', 1, 'A veces se le llama "vaca marina".', 'Los manatíes son herbívoros y pueden pesar hasta 500 kg.'),
(9, '¿Cómo se protegen legalmente los manglares?', '["Declarándolos Áreas Naturales Protegidas", "Poniéndoles rejas", "Pintándolos de rojo"]', 0, 'Las leyes prohíben su tala injustificada.', 'En muchos países, cortar un mangle es un delito federal.'),
(9, '¿Qué insectos son comunes en el manglar al atardecer?', '["Mosquitos", "Abejas", "Hormigas del desierto"]', 0, 'Son famosos por sus picaduras.', 'Aunque molestos, los mosquitos son base alimenticia para aves y peces.'),
(9, '¿Qué puedes hacer tú para proteger los manglares?', '["Consumir camarón sustentable y no tirar basura", "Cortar árboles", "Pescar todo lo posible"]', 0, 'Apoyar prácticas pesqueras que no destruyan su hábitat.', 'El ecoturismo responsable ayuda a las comunidades a cuidar el manglar.');

-- ── BIOMA 3: ARRECIFE (Niveles 10 al 14) ────────────────────────────────
INSERT INTO questions (level_id, question_text, options, correct_index, hint, fun_fact) VALUES
-- Nivel 10
(10, '¿Qué es un coral?', '["Una roca inerte", "Un animal invertebrado", "Una planta submarina"]', 1, 'Aunque parecen piedras, están formados por pólipos vivos.', 'Los corales son parientes de las medusas y las anémonas.'),
(10, '¿Qué causa el "blanqueamiento" del coral?', '["El agua muy fría", "El estrés por calentamiento del agua", "Pintura blanca"]', 1, 'Cuando hace mucho calor, expulsan a las algas que les dan color.', 'Un coral blanqueado no está muerto aún, pero puede morir de hambre si no se recupera.'),
(10, '¿Quién le da el color y alimento al coral?', '["Pequeñas algas llamadas zooxantelas", "Peces de colores", "El sol"]', 0, 'Viven dentro del tejido del coral en simbiosis.', 'Las zooxantelas hacen fotosíntesis, por eso los corales necesitan luz solar.'),
(10, '¿Por qué se llaman las "selvas del mar"?', '["Porque hay monos nadando", "Por su increíble biodiversidad (variedad de vida)", "Porque son de color verde oscuro"]', 1, 'Albergan muchas especies diferentes.', 'Los arrecifes ocupan el 1% del océano, pero albergan el 25% de la vida marina.'),
(10, '¿Qué protector solar es seguro para los arrecifes?', '["Cualquiera", "Los que contienen oxibenzona", "Los que son libres de químicos tóxicos (biodegradables)"]', 2, 'Los químicos dañan a los corales.', 'Hawái fue el primer estado de EE. UU. en prohibir bloqueadores con oxibenzona.'),
-- Nivel 11
(11, '¿Qué pez ayuda a limpiar los corales comiendo algas?', '["El pez loro", "El tiburón", "El pez globo"]', 0, 'Su boca parece un pico de ave.', 'El pez loro come coral muerto y hace caca en forma de arena blanca.'),
(11, '¿Qué forma tiene el coral cerebro?', '["Forma de estrella", "Parece un cerebro humano", "Es plano"]', 1, 'Tiene surcos y crestas curvas.', 'Pueden vivir cientos de años y crecer a tamaños gigantescos.'),
(11, '¿Cómo se protegen las tortugas en los arrecifes?', '["Tirándoles plástico", "Escondiéndose en su caparazón y buscando refugio", "Mordiéndolos"]', 1, 'El caparazón es su escudo natural.', 'Las tortugas de carey ayudan a los corales comiéndose las esponjas invasoras.'),
(11, '¿Qué tipo de ecosistema es el Sistema Arrecifal Mesoamericano?', '["El segundo arrecife de barrera más grande del mundo", "Un pequeño lago", "Un arrecife artificial"]', 0, 'Solo la Gran Barrera de Australia es más grande.', 'Abarca México, Belice, Guatemala y Honduras.'),
(11, '¿Por qué no debes tocar los corales al bucear?', '["Te pueden quemar y ellos pueden infectarse y morir", "Porque son pegajosos", "Para que no te muerdan"]', 0, 'Nuestra grasa de la piel los lastima.', 'Los corales crecen extremadamente lento, ¡apenas 1 a 10 cm por año!'),
-- Nivel 12
(12, '¿Qué estrella de mar es enemiga de los corales?', '["Estrella roja", "Corona de espinas", "Estrella azul"]', 1, 'Tiene púas venenosas y se come al coral vivo.', 'Un brote de estas estrellas puede destruir hectáreas de coral rápidamente.'),
(12, '¿Qué es la acidificación de los océanos?', '["Ponerle limón al mar", "El océano absorbe CO2 y se vuelve más ácido, disolviendo conchas y corales", "Agua más dulce"]', 1, 'Afecta la capacidad del coral para crear su esqueleto de calcio.', 'El pH del océano ha disminuido significativamente desde la revolución industrial.'),
(12, '¿Cuál es un método humano para restaurar arrecifes?', '["Plantar corales cultivados en guarderías marinas", "Pintar rocas de colores", "Dejarlos secar"]', 0, 'Se cortan pedacitos para que crezcan y luego se trasplantan.', 'Las guarderías de coral pueden acelerar el crecimiento del coral.'),
(12, '¿Qué pez venenoso con rayas y espinas largas es una plaga en América?', '["El pez payaso", "El pez león", "El pez vela"]', 1, 'No es originario del Caribe y come de todo.', 'El pez león es originario del Indo-Pacífico; en el Caribe no tiene depredadores naturales.'),
(12, '¿Qué relación tienen el pez payaso y la anémona?', '["El pez payaso se come a la anémona", "Mutualismo: se protegen mutuamente", "Se odian"]', 1, 'Son mejores amigos en el océano.', 'El pez payaso tiene una capa de mucosa que evita que la anémona lo pique.'),
-- Nivel 13
(13, '¿Qué sucede cuando hay demasiados nutrientes (fertilizantes) en el arrecife?', '["Las algas crecen demasiado y asfixian al coral", "Los corales engordan", "El agua se vuelve transparente"]', 0, 'Las algas compiten por el espacio y bloquean la luz.', 'El exceso de fertilizantes agrícolas llega al mar a través de los ríos.'),
(13, '¿Qué papel juegan los tiburones en el arrecife?', '["Son los depredadores tope que mantienen el equilibrio", "Se comen todo el coral", "Son mascotas"]', 0, 'Si desaparecen, se altera toda la cadena alimenticia.', 'Los tiburones de arrecife suelen cazar de noche y descansar de día.'),
(13, '¿De qué material está hecho el esqueleto de un coral duro?', '["De hierro", "De plástico", "Carbonato de calcio (piedra caliza)"]', 2, 'Es el mismo material que el de una tiza (gis) o concha marina.', 'Con el tiempo, estos esqueletos forman las gigantescas estructuras del arrecife.'),
(13, '¿Qué es la pesca con dinamita?', '["Un método destructivo que vuela el coral para matar peces", "Un juego acuático", "Pescar de noche"]', 0, 'Usa explosivos y está prohibida.', 'Destruye siglos de crecimiento de coral en un solo segundo.'),
(13, '¿Cómo afectan las anclas de los barcos al arrecife?', '["Los peinan", "Rompen los corales físicamente", "Los alimentan"]', 1, 'Al tirar anclas sobre el coral, lo parten en pedazos.', 'Se deben usar boyas de amarre fijas para evitar anclar en el arrecife.'),
-- Nivel 14
(14, '¿Por qué debemos reducir el uso de plástico para salvar el coral?', '["El coral se enferma al enredarse en plástico o ingerir microplásticos", "Al coral no le importa", "El plástico lo calienta"]', 0, 'Los microplásticos transmiten bacterias al tejido del coral.', 'Se calcula que hay miles de millones de trozos de plástico atrapados en arrecifes.'),
(14, '¿Qué son los corales blandos?', '["Corales de gelatina", "Corales sin esqueleto duro, como los abanicos de mar", "Algas marinas"]', 1, 'Se balancean con las corrientes de agua.', 'Los corales blandos usan pequeñas espinas de calcio para darse estructura.'),
(14, '¿Qué es la marea roja?', '["Un crecimiento excesivo de microalgas tóxicas", "Agua pintada", "Peces rojos nadando juntos"]', 0, 'Ocurre por contaminación o exceso de nutrientes.', 'La marea roja puede matar miles de peces y afectar la salud humana.'),
(14, '¿Qué hacen las esponjas de mar en el arrecife?', '["Pintan el agua", "Filtran enormes cantidades de agua", "Comen tiburones"]', 1, 'Limpian el agua bombeándola a través de su cuerpo.', 'Una esponja del tamaño de una pelota de béisbol puede filtrar 50 litros de agua al día.'),
(14, '¿Cuál es la acción más importante a nivel global para salvar los arrecifes?', '["Bucear más", "Frenar el Cambio Climático", "Alimentar a los peces"]', 1, 'Evitar que el océano siga calentándose.', 'Si el planeta se calienta 2°C más, podríamos perder el 99% de los corales.');

-- ── BIOMA 4: BOSQUE (Niveles 15 al 19) ──────────────────────────────────
INSERT INTO questions (level_id, question_text, options, correct_index, hint, fun_fact) VALUES
-- Nivel 15
(15, '¿Qué proceso realizan los árboles para limpiar el aire?', '["Fotosíntesis", "Respiración animal", "Digestión"]', 0, 'Transforman el dióxido de carbono en oxígeno.', 'Durante la fotosíntesis, los árboles usan luz solar para fabricar su propio alimento.'),
(15, '¿Qué animal del bosque ibérico/mexicano está en peligro de extinción?', '["El oso hormiguero", "El lobo ibérico/Lobo mexicano", "El pingüino"]', 1, 'Es un cánido salvaje que aúlla a la luna.', 'El lobo mexicano estuvo a punto de desaparecer y hoy se reproduce en cautiverio.'),
(15, '¿Qué función cumplen los hongos en el bosque?', '["Descomponer materia muerta y reciclar nutrientes", "Cazar venados", "Hacer fotosíntesis"]', 0, 'Son los basureros y recicladores de la naturaleza.', 'Sin los hongos, el bosque se llenaría rápidamente de hojas muertas y troncos caídos.'),
(15, '¿Qué es la deforestación?', '["Cortar los árboles masivamente sin replantar", "Regar los árboles", "Pintar los troncos"]', 0, 'Es eliminar grandes áreas de bosque para usar el suelo.', 'La deforestación contribuye gravemente al cambio climático.'),
(15, '¿Por qué son importantes las hojas caídas en el suelo del bosque?', '["Crean una capa de abono llamada humus", "Hacen que te resbales", "No sirven de nada"]', 0, 'Se descomponen y alimentan el suelo.', 'La capa de hojas caídas también retiene la humedad del suelo.'),
-- Nivel 16
(16, '¿Qué es un bosque templado?', '["Un bosque con estaciones marcadas (otoño, invierno, etc.)", "Un bosque de cactus", "Un bosque congelado"]', 0, 'Aquí las hojas suelen caer en otoño.', 'Los bosques templados cubren gran parte del hemisferio norte.'),
(16, '¿Cómo previenen los árboles la erosión del suelo?', '["Sus raíces amarran la tierra", "Poniendo barreras de madera", "Gritando"]', 0, 'Funcionan como una red subterránea.', 'Sin árboles, la lluvia arrastraría la tierra fértil hacia los ríos.'),
(16, '¿Qué son los anillos del tronco de un árbol?', '["Círculos pintados", "Líneas que indican la edad del árbol y el clima pasado", "Marcas de gusanos"]', 1, 'Un anillo por cada año de vida.', 'Los anillos gruesos indican años de mucha lluvia y buen clima.'),
(16, '¿Por qué no debemos dejar fogatas encendidas en el bosque?', '["Porque los osos cocinan", "Porque pueden causar incendios forestales incontrolables", "Para que no haga calor"]', 1, 'El fuego puede propagarse rápidamente con el viento.', 'El 90% de los incendios forestales son causados por humanos.'),
(16, '¿Qué pájaro ayuda a plantar árboles escondiendo bellotas?', '["El colibrí", "El arrendajo o pájaro carpintero", "El pelícano"]', 1, 'Esconden semillas para el invierno y olvidan algunas.', 'Estos olvidos son el origen de miles de nuevos robles y encinos.'),
-- Nivel 17
(17, '¿Qué es una especie endémica?', '["Una planta o animal que solo existe en una región específica", "Una especie de otro planeta", "Una especie extinta"]', 0, 'Significa que es única de ese lugar.', 'Proteger los bosques protege a estas especies irreemplazables.'),
(17, '¿Qué animal del bosque usa ecolocalización para cazar de noche?', '["El búho", "El murciélago", "El ciervo"]', 1, 'Emiten sonidos agudos y escuchan el eco.', 'Los murciélagos controlan plagas al comer miles de insectos por noche.'),
(17, '¿Qué significa que un árbol sea caducifolio?', '["Que siempre está verde", "Que pierde todas sus hojas en invierno u otoño", "Que tiene espinas"]', 1, 'Se "queda calvo" para ahorrar energía en el frío.', 'En primavera, las hojas vuelven a brotar rápidamente.'),
(17, '¿Cómo afecta la tala ilegal a la fauna?', '["Les destruye su hogar y fuente de alimento", "Les da más espacio para correr", "No los afecta"]', 0, 'Quita árboles que usan para anidar y esconderse.', 'La tala ilegal mueve miles de millones de dólares en el mercado negro.'),
(17, '¿Qué gas absorben los árboles para ayudar a frenar el calentamiento global?', '["Oxígeno", "Helio", "Dióxido de carbono (CO2)"]', 2, 'Es el gas que emitimos con los autos.', 'Un bosque actúa como un gigantesco "sumidero de carbono".'),
-- Nivel 18
(18, '¿Qué es el sotobosque?', '["La capa de arbustos y plantas pequeñas debajo de los grandes árboles", "La parte más alta del árbol", "Un tipo de hongo"]', 0, 'Es la zona baja, húmeda y con poca luz.', 'Muchos mamíferos y reptiles viven exclusivamente en el sotobosque.'),
(18, '¿Qué insecto del bosque es un gran polinizador?', '["La hormiga", "La abeja", "La cucaracha"]', 1, 'Tienen rayas amarillas y negras.', 'Se dice que uno de cada tres alimentos que consumimos depende de las abejas.'),
(18, '¿Por qué el musgo es útil en el bosque?', '["Actúa como esponja, reteniendo el agua", "Para resbalarse", "Para decorar"]', 0, 'Es una pequeña planta verde sin raíces profundas.', 'El musgo puede absorber hasta 20 veces su peso en agua.'),
(18, '¿Qué animal es un ingeniero del ecosistema construyendo presas?', '["El lobo", "El castor", "El zorro"]', 1, 'Tienen dientes grandes y cola plana.', 'Las presas de los castores crean humedales que benefician a muchas especies.'),
(18, '¿Cuál es el principal depredador en los bosques del norte?', '["El puma o lobo", "El conejo", "La ardilla"]', 0, 'Mantienen las poblaciones de herbívoros bajo control.', 'Si no hubiera pumas o lobos, los venados se comerían toda la vegetación.'),
-- Nivel 19
(19, '¿Cómo podemos usar papel sin dañar tanto el bosque?', '["Usando papel reciclado o certificado FSC", "Imprimiendo hojas en blanco", "Comprando más libros nuevos"]', 0, 'La certificación FSC asegura que el árbol fue replantado.', 'Reciclar una tonelada de papel salva aproximadamente 17 árboles maduros.'),
(19, '¿Qué papel juegan los insectos descomponedores?', '["Se comen el plástico", "Trituran la madera muerta devolviendo nutrientes", "Destruyen árboles sanos"]', 1, 'Como los escarabajos y termitas.', 'Son esenciales para que la tierra vuelva a ser fértil.'),
(19, '¿Por qué la biodiversidad es mayor en bosques maduros?', '["Porque tienen una estructura más compleja de diferentes edades", "Porque los árboles son todos iguales", "Porque no hay animales"]', 0, 'Tienen árboles caídos, jóvenes y viejos al mismo tiempo.', 'Un bosque antiguo no puede ser reemplazado fácilmente plantando un bosque nuevo.'),
(19, '¿Cómo afecta una carretera cruzando un bosque?', '["Fragmenta el hábitat y causa atropellamientos", "Ayuda a los animales a viajar rápido", "Planta más árboles"]', 0, 'Rompe el bosque en dos pedazos pequeños.', 'Para solucionarlo, algunos países construyen "puentes verdes" para animales.'),
(19, '¿Qué es la reforestación?', '["Cortar el bosque", "Plantar árboles nuevos en áreas deforestadas", "Lavar los árboles"]', 1, 'Es devolverle al bosque lo que se le quitó.', 'Reforestar con especies nativas es más exitoso que usar especies exóticas.');

-- ── BIOMA 5: SELVA (Niveles 20 al 24) ──────────────────────────────────
INSERT INTO questions (level_id, question_text, options, correct_index, hint, fun_fact) VALUES
-- Nivel 20
(20, '¿Por qué a la Amazonía se le llama "el pulmón del mundo"?', '["Porque tiene forma de pulmón", "Porque produce muchísimo oxígeno y regula el clima", "Porque hace ruido al respirar"]', 1, 'Es el bosque tropical más grande del planeta.', 'Produce cerca del 20% del oxígeno del mundo.'),
(20, '¿Qué característica define a la selva tropical?', '["Mucho frío y nieve", "Calor, humedad y lluvias abundantes todo el año", "Clima seco"]', 1, 'Nunca hay invierno helado allí.', 'En algunas selvas llueve casi todos los días del año.'),
(20, '¿Dónde vive la mayor parte de los animales en la selva?', '["Bajo la tierra", "En el dosel (la parte alta de los árboles)", "En los ríos exclusivamente"]', 1, 'Están muy arriba, donde hay más luz y frutas.', 'Más del 50% de las especies de la selva nunca bajan al suelo.'),
(20, '¿Qué animal de la selva se mueve muy lento para ahorrar energía?', '["El jaguar", "El perezoso", "El mono araña"]', 1, 'Pasa su vida colgando boca abajo.', 'Se mueven tan lento que les crece un alga verde en el pelaje que los camufla.'),
(20, '¿Cómo es el suelo de la selva?', '["Muy rico en nutrientes", "Muy pobre en nutrientes porque la lluvia los lava", "Lleno de rocas de oro"]', 1, 'Sorprendentemente, la tierra no es fértil.', 'Toda la riqueza de nutrientes está en las plantas y árboles vivos, no en el suelo.'),
-- Nivel 21
(21, '¿Cuál es la mayor causa de destrucción de la selva amazónica?', '["Para crear campos de cultivo y ganadería", "Para hacer parques de diversiones", "Los incendios naturales"]', 0, 'Se tala para sembrar pasto para vacas o soya.', 'Se pierde un área de selva del tamaño de un campo de fútbol cada minuto.'),
(21, '¿Qué son las plantas epífitas (como orquídeas)?', '["Plantas que se comen a otras", "Plantas que crecen sobre las ramas de otros árboles para alcanzar luz", "Plantas que crecen en la oscuridad"]', 1, 'Usan a otros árboles como repisas, pero no son parásitas.', 'Obtienen su agua y nutrientes del aire y la lluvia.'),
(21, '¿Por qué los jaguares son importantes en la selva?', '["Son depredadores alfa que mantienen bajo control a otros herbívoros", "Plantan semillas", "Asustan a los cazadores"]', 0, 'Son los reyes felinos de la selva americana.', 'Sus manchas en forma de roseta les sirven de camuflaje perfecto entre las sombras.'),
(21, '¿Qué tribu humana ayuda a proteger las selvas?', '["Los turistas", "Los pueblos indígenas originarios", "Los leñadores"]', 1, 'Han vivido en equilibrio con la selva por miles de años.', 'Las tierras indígenas son las áreas mejor conservadas de la selva.'),
(21, '¿Qué insecto cultiva su propio hongo en la selva?', '["La hormiga cortadora de hojas", "La mariposa Morpho", "El escarabajo Hércules"]', 0, 'Llevan trocitos de hojas en su espalda.', 'No comen las hojas, las usan para cultivar un hongo del cual se alimentan.'),
-- Nivel 22
(22, '¿Qué fruta originaria de las selvas consumimos en barra?', '["La manzana", "El cacao (chocolate)", "El limón"]', 1, 'Los mayas y aztecas lo usaban como moneda.', 'La selva es el origen de muchos alimentos, como el plátano y el café.'),
(22, '¿Qué anfibio de colores brillantes es muy venenoso en la selva?', '["El sapo toro", "La rana dardo venenosa", "La iguana"]', 1, 'Sus colores advierten: "¡No me comas!".', 'Obtienen su veneno de los insectos que comen.'),
(22, '¿Qué es el "estrato emergente"?', '["La raíz del árbol", "Los árboles más gigantes que sobresalen por encima del dosel", "Un río subterráneo"]', 1, 'Son como rascacielos de la naturaleza.', 'Pueden medir más de 60 metros de altura y recibir el impacto directo del sol y viento.'),
(22, '¿Qué gran reptil domina los ríos de la selva amazónica?', '["El dragón de Komodo", "El caimán negro", "El cocodrilo del Nilo"]', 1, 'Es el mayor depredador del río Amazonas.', 'Puede llegar a medir hasta 6 metros de largo.'),
(22, '¿Qué pasa con la medicina si se destruye la selva?', '["Nada", "Perdemos curas potenciales para enfermedades, que están en las plantas", "Los hospitales cierran"]', 1, 'La selva es la farmacia más grande del mundo.', 'Más del 25% de las medicinas modernas provienen de plantas de la selva tropical.'),
-- Nivel 23
(23, '¿Qué es el contrabando de especies exóticas?', '["Sacar animales silvestres (loros, monos) para venderlos como mascotas ilegales", "Viajar con tu perro", "Comprar en el zoológico"]', 0, 'Es un negocio muy dañino para la biodiversidad.', 'De cada 10 animales traficados ilegalmente, 8 mueren en el camino.'),
(23, '¿Por qué los tucanes tienen picos tan grandes?', '["Para asustar", "Para alcanzar frutas lejanas y disipar el calor de su cuerpo", "Para cavar hoyos"]', 1, 'Funciona como un radiador que enfría su sangre.', 'A pesar de su tamaño, su pico es hueco y muy ligero.'),
(23, '¿Qué son las lianas?', '["Serpientes muy largas", "Enredaderas leñosas gruesas como cuerdas que cuelgan de los árboles", "Un tipo de mono"]', 1, 'Tarzán las usaba para balancearse.', 'Compiten intensamente con los árboles por la luz del sol.'),
(23, '¿Qué serpiente constrictora gigante vive en las selvas sudamericanas?', '["La cobra real", "La anaconda verde", "La serpiente de cascabel"]', 1, 'Vive gran parte del tiempo en el agua.', 'Es la serpiente más pesada del mundo, ¡puede pesar más de 100 kg!'),
(23, '¿Qué producto que usamos todos los días requiere plantaciones que destruyen la selva en Asia?', '["Aceite de oliva", "Aceite de palma", "Aceite de motor"]', 1, 'Se usa en galletas, champú y cosméticos.', 'Esta deforestación amenaza seriamente a los orangutanes.'),
-- Nivel 24
(24, '¿Cómo viaja la semilla de la castaña (nuez de Brasil)?', '["Se la lleva el viento", "Un roedor llamado agutí las esconde", "Flotando en el río"]', 1, 'El agutí tiene dientes lo bastante fuertes para abrir la dura cáscara.', 'Si no fuera por el agutí, este gran árbol no podría reproducirse.'),
(24, '¿Por qué los ríos de la selva a veces son de color café oscuro?', '["Están contaminados", "Llevan sedimentos de tierra y hojas descompuestas (ácidos húmicos)", "Están llenos de chocolate"]', 1, 'Se les conoce como ríos de aguas negras.', 'El Río Negro, en el Amazonas, es el río de aguas negras más grande del mundo.'),
(24, '¿Qué significa que la selva recicla su propia agua?', '["Los árboles sudan agua que forma nubes y vuelve a llover ahí mismo", "Usan tuberías", "El río se evapora rápido"]', 0, 'Este proceso se llama "ríos voladores".', 'Los árboles de la selva envían más agua a la atmósfera que el propio río Amazonas al mar.'),
(24, '¿Qué puedes comprar de forma certificada para ayudar a la selva?', '["Muebles de caoba sin certificar", "Productos con certificación de Rainforest Alliance (rana verde)", "Mascotas exóticas"]', 1, 'Busca el sello del sapito verde en el cacao o el café.', 'Esta certificación garantiza que se cultivó cuidando los bosques y a los trabajadores.'),
(24, '¿Cuál es el mayor peligro del avance de las carreteras en la selva?', '["Permiten el acceso a taladores y mineros ilegales a zonas vírgenes", "Hacen ruido", "Los animales se mudan a la ciudad"]', 0, 'Abre la puerta a la destrucción sistemática.', 'Donde se construye una carretera en la selva, rápidamente se deforestan los márgenes.');

-- ── BIOMA 6: DESIERTO (Niveles 25 al 29) ────────────────────────────────
INSERT INTO questions (level_id, question_text, options, correct_index, hint, fun_fact) VALUES
-- Nivel 25
(25, '¿Qué característica define principalmente a un desierto?', '["Mucho calor y arena", "Extrema escasez de lluvia o precipitación", "Que no hay animales"]', 1, 'No todos los desiertos son calientes.', 'La Antártida es el desierto más grande del mundo, pero es de hielo.'),
(25, '¿Cómo almacenan agua los cactus?', '["En botellas", "En sus tallos gruesos y carnosos", "En hojas gigantes"]', 1, 'Sus tallos se inflan como globos cuando llueve.', 'El cactus Saguaro puede absorber miles de litros de agua en una sola lluvia.'),
(25, '¿Por qué los cactus tienen espinas en lugar de hojas?', '["Para verse peligrosos", "Para evitar perder agua por evaporación y defenderse", "Para atrapar insectos"]', 1, 'Sin hojas planas, el sol no seca a la planta.', 'Las espinas también dan un poco de sombra al tallo del cactus.'),
(25, '¿Qué animal del desierto tiene joroba para almacenar grasa, no agua?', '["El caballo", "El camello", "El escorpión"]', 1, 'Esa grasa se convierte en energía y agua cuando lo necesitan.', 'Los camellos pueden pasar semanas sin beber agua.'),
(25, '¿Cómo evitan el calor del día muchos animales del desierto?', '["Usan sombrillas", "Son nocturnos y salen solo de noche", "Se meten a las albercas"]', 1, 'Se esconden en madrigueras subterráneas durante el día.', 'En la noche, el desierto puede volverse bastante frío.'),
-- Nivel 26
(26, '¿Qué es la desertificación?', '["Hacer un desierto de postre", "Cuando tierra fértil se vuelve desértica por sequía y deforestación", "Plantar cactus en la ciudad"]', 1, 'Es un gran problema causado por el mal manejo del suelo.', 'El pastoreo excesivo es una de las principales causas de desertificación.'),
(26, '¿Qué reptil venenoso habita en los desiertos americanos y hace ruido con la cola?', '["La anaconda", "La serpiente de cascabel", "La cobra"]', 1, 'Su cola suena como una maraca para advertir que te alejes.', 'El cascabel está hecho de queratina, el mismo material que nuestras uñas.'),
(26, '¿Cómo obtienen agua algunas ratas del desierto (ratas canguro)?', '["Tienen botellas escondidas", "Sacan el agua de las semillas secas que comen", "Cavan pozos"]', 1, 'Nunca necesitan beber agua líquida en toda su vida.', 'Tienen riñones especiales que producen una orina muy concentrada para no perder agua.'),
(26, '¿Qué gran ave de alas anchas vuela sobre los desiertos buscando animales muertos (carroña)?', '["El zopilote o cóndor", "El colibrí", "El pingüino"]', 0, 'Limpian el ecosistema eliminando la carne podrida.', 'El ácido de sus estómagos destruye bacterias que matarían a otros animales.'),
(26, '¿Por qué las orejas del zorro fénec (zorro del desierto) son tan grandes?', '["Para escuchar música", "Para disipar el calor de su cuerpo y oír presas bajo la arena", "Para volar"]', 1, 'Las orejas funcionan como pequeños aires acondicionados.', 'Es el zorro más pequeño del mundo, pero tiene las orejas más grandes en proporción.'),
-- Nivel 27
(27, '¿Qué son los oasis?', '["Espejismos de agua", "Zonas en el desierto donde hay un manantial o fuente de agua natural", "Una marca de bebida"]', 1, 'Son paraísos verdes en medio de la arena.', 'Los oasis permiten la vida de muchas palmeras y pequeños asentamientos humanos.'),
(27, '¿Qué arácnido del desierto levanta su aguijón curvo para atacar?', '["La tarántula", "El escorpión (alacrán)", "La garrapata"]', 1, 'Son cazadores nocturnos que brillan bajo luz ultravioleta.', 'Casi todos los escorpiones brillan de color cian fluorescente bajo luz negra.'),
(27, '¿Qué planta desértica "camina" empujada por el viento cuando está seca?', '["La planta rodadora o estepicursora", "El cactus saltarín", "El girasol"]', 0, 'Se ve mucho en las películas del viejo oeste.', 'Se seca y rueda para esparcir sus semillas a lo largo del desierto.'),
(27, '¿Qué es el "lagarto cornudo" (llora sangre)?', '["Un lagarto que dispara sangre por los ojos para defenderse", "Un dinosaurio", "Un lagarto que hace magia"]', 0, 'Su extraña táctica asusta a los depredadores.', 'La sangre que lanza tiene un químico que sabe horrible para coyotes y zorros.'),
(27, '¿Cómo afectan los vehículos todoterreno (cuatrimotos) al desierto?', '["Lo hacen ver más bonito", "Destruyen la costra biológica del suelo y madrigueras", "Plantan semillas"]', 1, 'Rompen la delicada capa de bacterias y musgos que sujeta la arena.', 'Una vez rota esta costra, el viento se lleva la tierra fértil causando tormentas de arena.'),
-- Nivel 28
(28, '¿Qué energía renovable es perfecta para aprovechar en el desierto?', '["Energía hidroeléctrica", "Energía solar", "Energía de las olas"]', 1, 'Sobra el recurso del sol y hay pocas nubes.', 'Los grandes parques solares en desiertos pueden alimentar ciudades enteras.'),
(28, '¿Cómo respira y pierde menos agua la planta de Aloe Vera?', '["Cierra sus poros (estomas) de día y los abre de noche", "Respira por las raíces", "No respira"]', 0, 'A este sistema se le llama fotosíntesis CAM.', 'Muchas plantas del desierto atrapan el CO2 de noche y hacen el resto del trabajo de día.'),
(28, '¿Qué mamífero con armadura dura habita algunas zonas desérticas y áridas?', '["El rinoceronte", "El armadillo", "La tortuga terrestre"]', 1, 'Se hace bolita cuando se asusta.', 'Su caparazón está hecho de hueso y piel muy dura.'),
(28, '¿Qué problema sufren los ríos que cruzan los desiertos?', '["El agua se seca antes de llegar al mar por sobreexplotación agrícola", "Se congelan", "Tienen demasiada agua"]', 0, 'Un ejemplo claro es el río Colorado.', 'El Río Colorado a veces no llega al Golfo de California porque le sacan toda el agua antes.'),
(28, '¿Cómo ayudan las arañas y alacranes en el desierto?', '["Controlan las poblaciones de otros insectos", "Hacen daño a las plantas", "Comen pasto"]', 0, 'Mantienen el equilibrio como pequeños depredadores.', 'Sin ellos, habría plagas incontrolables de langostas y otros insectos.'),
-- Nivel 29
(29, '¿Qué animal rápido y de patas largas correteaba "el Coyote" en las caricaturas?', '["El avestruz", "El correcaminos", "El emú"]', 1, 'Es un ave real que habita el desierto.', 'El correcaminos real rara vez vuela y prefiere correr hasta a 32 km/h para atrapar lagartijas.'),
(29, '¿Cómo recolectan agua algunos escarabajos del desierto de Namibia?', '["Compran botellas", "Levantan el cuerpo para atrapar la niebla de la mañana en su espalda", "Cavan hondo"]', 1, 'La humedad se condensa y resbala hasta su boca.', 'Este diseño del escarabajo inspiró tecnologías humanas para atrapar agua del aire.'),
(29, '¿Qué es un espejismo en el desierto?', '["Una ilusión óptica causada por el aire caliente doblando la luz", "Un lago real que desaparece", "Un fantasma"]', 0, 'Parece un charco de agua a lo lejos, pero es el reflejo del cielo.', 'Ocurre porque el aire cerca del suelo está mucho más caliente que el de arriba.'),
(29, '¿Cuál es el desierto cálido más grande de la Tierra?', '["El desierto de Sonora", "El desierto del Sahara", "El desierto de Gobi"]', 1, 'Está ubicado en África.', 'El Sahara es casi del tamaño de los Estados Unidos.'),
(29, '¿Por qué debemos proteger los ecosistemas del desierto?', '["Porque albergan especies adaptadas únicas y frágiles", "Porque no sirven para nada", "Para hacer más arena"]', 0, 'A pesar de verse vacíos, están llenos de vida especializada.', 'Un desierto dañado tarda decenas o cientos de años en recuperarse debido a la falta de agua.');
